name: Continuous Integration
# inspired by bcourses and https://github.com/actions/setup-python/blob/main/.github/workflows/test-python.yml

on: 
  push: 
    branches: 
      - main

jobs:
  run_tests:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: $${{matrix.os}}
    strategy: 
      fail-fast: false
      matrix:
        os: [macos-latest]
        python: [3.8.18]
    
    steps:
    # checkout codebase
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    # install python
    - name: setup-python ${{matrix.python}}
      id: setup-python
      uses: ./
      with: 
        python-version: ${{matrix.python}}

    - name: Validate version
      run: |
          $pythonVersion = (python --version)
          if ("Python ${{ matrix.python }}" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is ${{ matrix.python }}"
            exit 1
          }
          $pythonVersion
      shell: pwsh

    # install python dependencies
    - name: Install Dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
    
    # run actual unit tests
    - name: Test with unittest
      run: |
        python -m unittest tests.test_root
        
