name: Continuous Integration
# inspired by bcourses and https://github.com/actions/setup-python/blob/main/.github/workflows/test-python.yml

on: 
  push: 
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        python: [3.8.18]
    
    steps:
    # checkout codebase
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    # install python
    - name: Setup Python ${{matrix.python}}
      id: setup-python
      uses: ./
      with: 
        python-version: ${{matrix.python}}

    # install python dependencies
    - name: Install Dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
    
    # run actual unit tests
    - name: Test with unittest
      run: |
        python -m unittest tests.test_root
        
